sudo: required
services:
  - docker
before_install:
  - docker build -t santoshnikam1990/travistest:v1.0 .
script:
  - echo "$password" | docker login -u "$username" --password-stdin
  - docker images
  - docker push santoshnikam1990/travistest:v1.0
notifications:
  email:
    recipients:
      - santoshnikam198810@gmail.com
    on_success: always
    on_failure: always
